sudo: required

language: minimal

services:
  - docker

before_install:
  - docker pull krangelov/gf-wordnet

script:
  - docker run --mount src="$(pwd)",target=/home/gf-wordnet,type=bind krangelov/gf-wordnet /bin/bash -c "make SERVER=NO"
